UPDATE prospeccao SET mesorregiao = 'Triângulo Mineiro/Alto Paranaíba', microrregiao = 'Uberlândia' WHERE uf = 'MG' AND cidade = 'UBERLANDIA';
UPDATE prospeccao SET mesorregiao = 'Leste Alagoano', microrregiao = 'Maceió' WHERE uf = 'AL' AND cidade = 'MACEIO';
UPDATE prospeccao SET mesorregiao = 'Distrito Federal', microrregiao = 'Brasília' WHERE uf = 'DF' AND cidade = 'BRASILIA';
UPDATE prospeccao SET mesorregiao = 'Centro Goiano', microrregiao = 'Goiânia' WHERE uf = 'GO' AND cidade = 'GOIANIA';
UPDATE prospeccao SET mesorregiao = 'Norte Maranhense', microrregiao = 'Aglomeração Urbana de São Luís' WHERE uf = 'MA' AND cidade = 'SAO LUIS';
UPDATE prospeccao SET mesorregiao = 'Centro-Sul Mato-grossense', microrregiao = 'Cuiabá' WHERE uf = 'MT' AND cidade = 'CUIABA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Belém', microrregiao = 'Belém' WHERE uf = 'PA' AND cidade = 'BELEM';
UPDATE prospeccao SET mesorregiao = 'Nordeste Paraense', microrregiao = 'Bragantina' WHERE uf = 'PA' AND cidade = 'BRAGANCA';
UPDATE prospeccao SET mesorregiao = 'Sudeste Paraense', microrregiao = 'Parauapebas' WHERE uf = 'PA' AND cidade = 'CANAA DOS CARAJAS';
UPDATE prospeccao SET mesorregiao = 'Baixo Amazonas', microrregiao = 'Santarém' WHERE uf = 'PA' AND cidade = 'SANTAREM';
UPDATE prospeccao SET mesorregiao = 'Nordeste Paraense', microrregiao = 'Tomé-Açu' WHERE uf = 'PA' AND cidade = 'TAILANDIA';
UPDATE prospeccao SET mesorregiao = 'Mata Paraibana', microrregiao = 'João Pessoa' WHERE uf = 'PB' AND cidade = 'JOAO PESSOA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Recife', microrregiao = 'Recife' WHERE uf = 'PE' AND cidade = 'JABOATAO DOS GUARARAPES';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Curitiba', microrregiao = 'Curitiba' WHERE uf = 'PR' AND cidade = 'ALMIRANTE TAMANDARE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Curitiba', microrregiao = 'Curitiba' WHERE uf = 'PR' AND cidade = 'ARAUCARIA';
UPDATE prospeccao SET mesorregiao = 'Oeste Paranaense', microrregiao = 'Foz do Iguaçu' WHERE uf = 'PR' AND cidade = 'FOZ DO IGUACU';
UPDATE prospeccao SET mesorregiao = 'Sudoeste Paranaense', microrregiao = 'Francisco Beltrão' WHERE uf = 'PR' AND cidade = 'FRANCISCO BELTRAO';
UPDATE prospeccao SET mesorregiao = 'Centro Ocidental Paranaense', microrregiao = 'Goioerê' WHERE uf = 'PR' AND cidade = 'GOIOERE';
UPDATE prospeccao SET mesorregiao = 'Oeste Paranaense', microrregiao = 'Toledo' WHERE uf = 'PR' AND cidade = 'MARECHAL CANDIDO RONDON';
UPDATE prospeccao SET mesorregiao = 'Norte Central Paranaense', microrregiao = 'Maringá' WHERE uf = 'PR' AND cidade = 'MARINGA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Curitiba', microrregiao = 'Paranaguá' WHERE uf = 'PR' AND cidade = 'PARANAGUA';
UPDATE prospeccao SET mesorregiao = 'Noroeste Paranaense', microrregiao = 'Paranavaí' WHERE uf = 'PR' AND cidade = 'PARANAVAI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Curitiba', microrregiao = 'Curitiba' WHERE uf = 'PR' AND cidade = 'SAO JOSE DOS PINHAIS';
UPDATE prospeccao SET mesorregiao = 'Sul Fluminense', microrregiao = 'Barra do Piraí' WHERE uf = 'RJ' AND cidade = 'BARRA DO PIRAI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'ITABORAI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Itaguaí' WHERE uf = 'RJ' AND cidade = 'ITAGUAI';
UPDATE prospeccao SET mesorregiao = 'Norte Fluminense', microrregiao = 'Macaé' WHERE uf = 'RJ' AND cidade = 'MACAE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'MAGE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'MARICA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'NILOPOLIS';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'NITEROI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'NOVA IGUACU';
UPDATE prospeccao SET mesorregiao = 'Centro Fluminense', microrregiao = 'Três Rios' WHERE uf = 'RJ' AND cidade = 'PARAIBA DO SUL';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Serrana' WHERE uf = 'RJ' AND cidade = 'PETROPOLIS';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'SAO GONCALO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Rio de Janeiro' WHERE uf = 'RJ' AND cidade = 'SAO JOAO DE MERITI';
UPDATE prospeccao SET mesorregiao = 'Baixadas', microrregiao = 'Lagos' WHERE uf = 'RJ' AND cidade = 'SAO PEDRO DA ALDEIA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana do Rio de Janeiro', microrregiao = 'Serrana' WHERE uf = 'RJ' AND cidade = 'TERESOPOLIS';
UPDATE prospeccao SET mesorregiao = 'Centro Fluminense', microrregiao = 'Três Rios' WHERE uf = 'RJ' AND cidade = 'TRES RIOS';
UPDATE prospeccao SET mesorregiao = 'Sul Fluminense', microrregiao = 'Barra do Pira��' WHERE uf = 'RJ' AND cidade = 'VALENCA';
UPDATE prospeccao SET mesorregiao = 'Oeste Potiguar', microrregiao = 'Vale do Açu' WHERE uf = 'RN' AND cidade = 'ASSU';
UPDATE prospeccao SET mesorregiao = 'Leste Potiguar', microrregiao = 'Macaíba' WHERE uf = 'RN' AND cidade = 'CEARA-MIRIM';
UPDATE prospeccao SET mesorregiao = 'Central Potiguar', microrregiao = 'Serra de Santana' WHERE uf = 'RN' AND cidade = 'CERRO CORA';
UPDATE prospeccao SET mesorregiao = 'Agreste Potiguar', microrregiao = 'Baixa Verde' WHERE uf = 'RN' AND cidade = 'JOAO CAMARA';
UPDATE prospeccao SET mesorregiao = 'Oeste Potiguar', microrregiao = 'Mossoró' WHERE uf = 'RN' AND cidade = 'MOSSORO';
UPDATE prospeccao SET mesorregiao = 'Leste Rondoniense', microrregiao = 'Ji-Paraná' WHERE uf = 'RO' AND cidade = 'JI-PARANA';
UPDATE prospeccao SET mesorregiao = 'Sudoeste Rio-grandense', microrregiao = 'Campanha Meridional' WHERE uf = 'RS' AND cidade = 'BAGE';
UPDATE prospeccao SET mesorregiao = 'Nordeste Rio-grandense', microrregiao = 'Caxias do Sul' WHERE uf = 'RS' AND cidade = 'BENTO GONCALVES';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Osório' WHERE uf = 'RS' AND cidade = 'CAPAO DA CANOA';
UPDATE prospeccao SET mesorregiao = 'Sudeste Rio-grandense', microrregiao = 'Pelotas' WHERE uf = 'RS' AND cidade = 'CAPAO DO LEAO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Porto Alegre' WHERE uf = 'RS' AND cidade = 'GRAVATAI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Porto Alegre' WHERE uf = 'RS' AND cidade = 'GUAIBA';
UPDATE prospeccao SET mesorregiao = 'Noroeste Rio-grandense', microrregiao = 'Ijuí' WHERE uf = 'RS' AND cidade = 'IJUI';
UPDATE prospeccao SET mesorregiao = 'Noroeste Rio-grandense', microrregiao = 'Não-Me-Toque' WHERE uf = 'RS' AND cidade = 'NAO-ME-TOQUE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Gramado-Canela' WHERE uf = 'RS' AND cidade = 'NOVA PETROPOLIS';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Osório' WHERE uf = 'RS' AND cidade = 'OSORIO';
UPDATE prospeccao SET mesorregiao = 'Noroeste Rio-grandense', microrregiao = 'Carazinho' WHERE uf = 'RS' AND cidade = 'PALMEIRA DAS MISSOES';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Porto Alegre' WHERE uf = 'RS' AND cidade = 'PAROBE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Porto Alegre' WHERE uf = 'RS' AND cidade = 'SAO LEOPOLDO';
UPDATE prospeccao SET mesorregiao = 'Sudeste Rio-grandense', microrregiao = 'Pelotas' WHERE uf = 'RS' AND cidade = 'SAO LOURENCO DO SUL';
UPDATE prospeccao SET mesorregiao = 'Noroeste Rio-grandense', microrregiao = 'Santo Ângelo' WHERE uf = 'RS' AND cidade = 'SAO LUIZ GONZAGA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Osório' WHERE uf = 'RS' AND cidade = 'TRAMANDAI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Porto Alegre' WHERE uf = 'RS' AND cidade = 'VIAMAO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de Porto Alegre', microrregiao = 'Osório' WHERE uf = 'RS' AND cidade = 'XANGRI-LA';
UPDATE prospeccao SET mesorregiao = 'Sul Catarinense', microrregiao = 'Araranguá' WHERE uf = 'SC' AND cidade = 'ARARANGUA';
UPDATE prospeccao SET mesorregiao = 'Vale do Itajaí', microrregiao = 'Itajaí' WHERE uf = 'SC' AND cidade = 'BALNEARIO CAMBORIU';
UPDATE prospeccao SET mesorregiao = 'Grande Florianópolis', microrregiao = 'Florianópolis' WHERE uf = 'SC' AND cidade = 'BIGUACU';
UPDATE prospeccao SET mesorregiao = 'Oeste Catarinense', microrregiao = 'Joaçaba' WHERE uf = 'SC' AND cidade = 'CACADOR';
UPDATE prospeccao SET mesorregiao = 'Vale do Itajaí', microrregiao = 'Itajaí' WHERE uf = 'SC' AND cidade = 'CAMBORIU';
UPDATE prospeccao SET mesorregiao = 'Oeste Catarinense', microrregiao = 'Chapecó' WHERE uf = 'SC' AND cidade = 'CHAPECO';
UPDATE prospeccao SET mesorregiao = 'Oeste Catarinense', microrregiao = 'Concórdia' WHERE uf = 'SC' AND cidade = 'CONCORDIA';
UPDATE prospeccao SET mesorregiao = 'Norte Catarinense', microrregiao = 'Joinville' WHERE uf = 'SC' AND cidade = 'CORUPA';
UPDATE prospeccao SET mesorregiao = 'Sul Catarinense', microrregiao = 'Criciúma' WHERE uf = 'SC' AND cidade = 'CRICIUMA';
UPDATE prospeccao SET mesorregiao = 'Oeste Catarinense', microrregiao = 'Chapecó' WHERE uf = 'SC' AND cidade = 'CUNHA PORA';
UPDATE prospeccao SET mesorregiao = 'Grande Florianópolis', microrregiao = 'Florianópolis' WHERE uf = 'SC' AND cidade = 'FLORIANOPOLIS';
UPDATE prospeccao SET mesorregiao = 'Vale do Itajaí', microrregiao = 'Itajaí' WHERE uf = 'SC' AND cidade = 'ITAJAI';
UPDATE prospeccao SET mesorregiao = 'Norte Catarinense', microrregiao = 'Joinville' WHERE uf = 'SC' AND cidade = 'ITAPOA';
UPDATE prospeccao SET mesorregiao = 'Norte Catarinense', microrregiao = 'Joinville' WHERE uf = 'SC' AND cidade = 'JARAGUA DO SUL';
UPDATE prospeccao SET mesorregiao = 'Serrana', microrregiao = 'Campos de Lages' WHERE uf = 'SC' AND cidade = 'OTACILIO COSTA';
UPDATE prospeccao SET mesorregiao = 'Grande Florianópolis', microrregiao = 'Florianópolis' WHERE uf = 'SC' AND cidade = 'PALHOCA';
UPDATE prospeccao SET mesorregiao = 'Norte Catarinense', microrregiao = 'Joinville' WHERE uf = 'SC' AND cidade = 'SAO FRANCISCO DO SUL';
UPDATE prospeccao SET mesorregiao = 'Grande Florianópolis', microrregiao = 'Tijucas' WHERE uf = 'SC' AND cidade = 'SAO JOAO BATISTA';
UPDATE prospeccao SET mesorregiao = 'Grande Florianópolis', microrregiao = 'Florianópolis' WHERE uf = 'SC' AND cidade = 'SAO JOSE';
UPDATE prospeccao SET mesorregiao = 'Sul Catarinense', microrregiao = 'Tubarão' WHERE uf = 'SC' AND cidade = 'TUBARAO';
UPDATE prospeccao SET mesorregiao = 'Araçatuba', microrregiao = 'Araçatuba' WHERE uf = 'SP' AND cidade = 'ARACATUBA';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Sorocaba' WHERE uf = 'SP' AND cidade = 'ARACOIABA DA SERRA';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'Bananal' WHERE uf = 'SP' AND cidade = 'ARAPEI';
UPDATE prospeccao SET mesorregiao = 'Marília', microrregiao = 'Tupã' WHERE uf = 'SP' AND cidade = 'ARCO-IRIS';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Bauru' WHERE uf = 'SP' AND cidade = 'AREIOPOLIS';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Guarulhos' WHERE uf = 'SP' AND cidade = 'ARUJA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Bauru' WHERE uf = 'SP' AND cidade = 'AVAI';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Avaré' WHERE uf = 'SP' AND cidade = 'AVARE';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'São José do Rio Preto' WHERE uf = 'SP' AND cidade = 'BALSAMO';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Itapeva' WHERE uf = 'SP' AND cidade = 'BARAO DE ANTONINA';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Capão Bonito' WHERE uf = 'SP' AND cidade = 'BARRA DO CHAPEU';
UPDATE prospeccao SET mesorregiao = 'Araraquara', microrregiao = 'Araraquara' WHERE uf = 'SP' AND cidade = 'BOA ESPERANCA DO SUL';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Bragança Paulista' WHERE uf = 'SP' AND cidade = 'BOM JESUS DOS PERDOES';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Itapeva' WHERE uf = 'SP' AND cidade = 'BOM SUCESSO DE ITARARE';
UPDATE prospeccao SET mesorregiao = 'Assis', microrregiao = 'Assis' WHERE uf = 'SP' AND cidade = 'BORA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Jaú' WHERE uf = 'SP' AND cidade = 'BORACEIA';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Bragança Paulista' WHERE uf = 'SP' AND cidade = 'BRAGANCA PAULISTA';
UPDATE prospeccao SET mesorregiao = 'Araçatuba', microrregiao = 'Birigui' WHERE uf = 'SP' AND cidade = 'BRAUNA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Bauru' WHERE uf = 'SP' AND cidade = 'CABRALIA PAULISTA';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Sorocaba' WHERE uf = 'SP' AND cidade = 'CABREUVA';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'São José dos Campos' WHERE uf = 'SP' AND cidade = 'CACAPAVA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Lins' WHERE uf = 'SP' AND cidade = 'CAFELANDIA';
UPDATE prospeccao SET mesorregiao = 'Presidente Prudente', microrregiao = 'Presidente Prudente' WHERE uf = 'SP' AND cidade = 'CAIUA';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'Campos do Jordão' WHERE uf = 'SP' AND cidade = 'CAMPOS DO JORDAO';
UPDATE prospeccao SET mesorregiao = 'Litoral Sul Paulista', microrregiao = 'Registro' WHERE uf = 'SP' AND cidade = 'CANANEIA';
UPDATE prospeccao SET mesorregiao = 'Assis', microrregiao = 'Assis' WHERE uf = 'SP' AND cidade = 'CANDIDO MOTA';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'Jaboticabal' WHERE uf = 'SP' AND cidade = 'CANDIDO RODRIGUES';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Capão Bonito' WHERE uf = 'SP' AND cidade = 'CAPAO BONITO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Osasco' WHERE uf = 'SP' AND cidade = 'CARAPICUIBA';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'Batatais' WHERE uf = 'SP' AND cidade = 'CASSIA DOS COQUEIROS';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'Catanduva' WHERE uf = 'SP' AND cidade = 'CATIGUA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Avaré' WHERE uf = 'SP' AND cidade = 'CERQUEIRA CESAR';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Tatuí' WHERE uf = 'SP' AND cidade = 'CESARIO LANGE';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'Barretos' WHERE uf = 'SP' AND cidade = 'COLOMBIA';
UPDATE prospeccao SET mesorregiao = 'Piracicaba', microrregiao = 'Limeira' WHERE uf = 'SP' AND cidade = 'CORDEIROPOLIS';
UPDATE prospeccao SET mesorregiao = 'Piracicaba', microrregiao = 'Rio Claro' WHERE uf = 'SP' AND cidade = 'CORUMBATAI';
UPDATE prospeccao SET mesorregiao = 'Campinas', microrregiao = 'Campinas' WHERE uf = 'SP' AND cidade = 'COSMOPOLIS';
UPDATE prospeccao SET mesorregiao = 'Assis', microrregiao = 'Assis' WHERE uf = 'SP' AND cidade = 'CRUZALIA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Santos' WHERE uf = 'SP' AND cidade = 'CUBATAO';
UPDATE prospeccao SET mesorregiao = 'Campinas', microrregiao = 'São João da Boa Vista' WHERE uf = 'SP' AND cidade = 'DIVINOLANDIA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Jaú' WHERE uf = 'SP' AND cidade = 'DOIS CORREGOS';
UPDATE prospeccao SET mesorregiao = 'Marília', microrregiao = 'Marília' WHERE uf = 'SP' AND cidade = 'ECHAPORA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Itapecerica da Serra' WHERE uf = 'SP' AND cidade = 'EMBU-GUACU';
UPDATE prospeccao SET mesorregiao = 'Campinas', microrregiao = 'São João da Boa Vista' WHERE uf = 'SP' AND cidade = 'ESPIRITO SANTO DO PINHAL';
UPDATE prospeccao SET mesorregiao = 'Assis', microrregiao = 'Ourinhos' WHERE uf = 'SP' AND cidade = 'ESPIRITO SANTO DO TURVO';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'Fernandópolis' WHERE uf = 'SP' AND cidade = 'FERNANDOPOLIS';
UPDATE prospeccao SET mesorregiao = 'Presidente Prudente', microrregiao = 'Adamantina' WHERE uf = 'SP' AND cidade = 'FLORIDA PAULISTA';
UPDATE prospeccao SET mesorregiao = 'Marília', microrregiao = 'Marília' WHERE uf = 'SP' AND cidade = 'GALIA';
UPDATE prospeccao SET mesorregiao = 'Marília', microrregiao = 'Marília' WHERE uf = 'SP' AND cidade = 'GARCA';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'Auriflama' WHERE uf = 'SP' AND cidade = 'GASTAO VIDIGAL';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Lins' WHERE uf = 'SP' AND cidade = 'GUAICARA';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'São Joaquim da Barra' WHERE uf = 'SP' AND cidade = 'GUAIRA';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'São José do Rio Preto' WHERE uf = 'SP' AND cidade = 'GUAPIACU';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'Ituverava' WHERE uf = 'SP' AND cidade = 'GUARA';
UPDATE prospeccao SET mesorregiao = 'Araçatuba', microrregiao = 'Andradina' WHERE uf = 'SP' AND cidade = 'GUARACAI';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Bauru' WHERE uf = 'SP' AND cidade = 'GUARANTA';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'Guaratinguetá' WHERE uf = 'SP' AND cidade = 'GUARATINGUETA';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Itapetininga' WHERE uf = 'SP' AND cidade = 'GUAREI';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Santos' WHERE uf = 'SP' AND cidade = 'GUARUJA';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'Ribeirão Preto' WHERE uf = 'SP' AND cidade = 'GUATAPARA';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'Auriflama' WHERE uf = 'SP' AND cidade = 'GUZOLANDIA';
UPDATE prospeccao SET mesorregiao = 'Marília', microrregiao = 'Tupã' WHERE uf = 'SP' AND cidade = 'HERCULANDIA';
UPDATE prospeccao SET mesorregiao = 'Campinas', microrregiao = 'Campinas' WHERE uf = 'SP' AND cidade = 'HORTOLANDIA';
UPDATE prospeccao SET mesorregiao = 'Araraquara', microrregiao = 'São Carlos' WHERE uf = 'SP' AND cidade = 'IBATE';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'São José do Rio Preto' WHERE uf = 'SP' AND cidade = 'IBIRA';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Piedade' WHERE uf = 'SP' AND cidade = 'IBIUNA';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'São José do Rio Preto' WHERE uf = 'SP' AND cidade = 'ICEM';
UPDATE prospeccao SET mesorregiao = 'Assis', microrregiao = 'Assis' WHERE uf = 'SP' AND cidade = 'IEPE';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Jaú' WHERE uf = 'SP' AND cidade = 'IGARACU DO TIETE';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'São José dos Campos' WHERE uf = 'SP' AND cidade = 'IGARATA';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'Fernandópolis' WHERE uf = 'SP' AND cidade = 'INDIAPORA';
UPDATE prospeccao SET mesorregiao = 'Presidente Prudente', microrregiao = 'Adamantina' WHERE uf = 'SP' AND cidade = 'INUBIA PAULISTA';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Sorocaba' WHERE uf = 'SP' AND cidade = 'IPERO';
UPDATE prospeccao SET mesorregiao = 'Piracicaba', microrregiao = 'Rio Claro' WHERE uf = 'SP' AND cidade = 'IPEUNA';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'São José do Rio Preto' WHERE uf = 'SP' AND cidade = 'IPIGUA';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'São Joaquim da Barra' WHERE uf = 'SP' AND cidade = 'IPUA';
UPDATE prospeccao SET mesorregiao = 'Piracicaba', microrregiao = 'Limeira' WHERE uf = 'SP' AND cidade = 'IRACEMAPOLIS';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'Novo Horizonte' WHERE uf = 'SP' AND cidade = 'IRAPUA';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Itapeva' WHERE uf = 'SP' AND cidade = 'ITABERA';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Avaré' WHERE uf = 'SP' AND cidade = 'ITAI';
UPDATE prospeccao SET mesorregiao = 'Litoral Sul Paulista', microrregiao = 'Itanhaém' WHERE uf = 'SP' AND cidade = 'ITANHAEM';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Capão Bonito' WHERE uf = 'SP' AND cidade = 'ITAPIRAPUA PAULISTA';
UPDATE prospeccao SET mesorregiao = 'Araraquara', microrregiao = 'Araraquara' WHERE uf = 'SP' AND cidade = 'ITAPOLIS';
UPDATE prospeccao SET mesorregiao = 'Bauru', microrregiao = 'Jaú' WHERE uf = 'SP' AND cidade = 'ITAPUI';
UPDATE prospeccao SET mesorregiao = 'Itapetininga', microrregiao = 'Itapeva' WHERE uf = 'SP' AND cidade = 'ITARARE';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'São José dos Campos' WHERE uf = 'SP' AND cidade = 'JACAREI';
UPDATE prospeccao SET mesorregiao = 'Macro Metropolitana Paulista', microrregiao = 'Jundiaí' WHERE uf = 'SP' AND cidade = 'JUNDIAI';
UPDATE prospeccao SET mesorregiao = 'Marília', microrregiao = 'Marília' WHERE uf = 'SP' AND cidade = 'MARILIA';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'São Paulo' WHERE uf = 'SP' AND cidade = 'MAUA';
UPDATE prospeccao SET mesorregiao = 'Ribeirão Preto', microrregiao = 'Ribeirão Preto' WHERE uf = 'SP' AND cidade = 'RIBEIRAO PRETO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'São Paulo' WHERE uf = 'SP' AND cidade = 'SANTO ANDRE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'São Paulo' WHERE uf = 'SP' AND cidade = 'SAO BERNARDO DO CAMPO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'São Paulo' WHERE uf = 'SP' AND cidade = 'SAO CAETANO DO SUL';
UPDATE prospeccao SET mesorregiao = 'Araraquara', microrregiao = 'São Carlos' WHERE uf = 'SP' AND cidade = 'SAO CARLOS';
UPDATE prospeccao SET mesorregiao = 'São José do Rio Preto', microrregiao = 'São José do Rio Preto' WHERE uf = 'SP' AND cidade = 'SAO JOSE DO RIO PRETO';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'São José dos Campos' WHERE uf = 'SP' AND cidade = 'SAO JOSE DOS CAMPOS';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'São Paulo' WHERE uf = 'SP' AND cidade = 'SAO PAULO';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Santos' WHERE uf = 'SP' AND cidade = 'SAO VICENTE';
UPDATE prospeccao SET mesorregiao = 'Campinas', microrregiao = 'Campinas' WHERE uf = 'SP' AND cidade = 'SUMARE';
UPDATE prospeccao SET mesorregiao = 'Metropolitana de São Paulo', microrregiao = 'Itapecerica da Serra' WHERE uf = 'SP' AND cidade = 'TABOAO DA SERRA';
UPDATE prospeccao SET mesorregiao = 'Vale do Paraíba Paulista', microrregiao = 'São José dos Campos' WHERE uf = 'SP' AND cidade = 'TAUBATE';