-- Adicionar campos de ficha técnica e laudo ao portfolio_produtos
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS material text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS dimensoes text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS peso_kg numeric(10,2);
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS norma_aplicavel text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS laudo_url text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS laudo_descricao text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS ficha_tecnica text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS vantagens text;
ALTER TABLE portfolio_produtos ADD COLUMN IF NOT EXISTS aplicacoes text;

-- Tabela de concorrentes para comparativo
CREATE TABLE IF NOT EXISTS portfolio_concorrentes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id bigint REFERENCES portfolio_produtos(id) ON DELETE CASCADE,
  concorrente text NOT NULL,
  produto_concorrente text,
  material text,
  metodo text,
  preco_ref text,
  vantagem_pousinox text,
  desvantagem_concorrente text,
  criado_em timestamptz DEFAULT now()
);

-- RLS
ALTER TABLE portfolio_concorrentes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_full" ON portfolio_concorrentes USING (auth.role() = 'service_role');

-- Seed: comparativo fixador Pousinox vs CFX RAI-FIX
INSERT INTO portfolio_concorrentes (concorrente, produto_concorrente, material, metodo, preco_ref, vantagem_pousinox, desvantagem_concorrente)
SELECT 'CFX RAI-FIX', 'Grampo externo para fachada', 'Aço galvanizado/inox', 'Grampo externo visível fixado sobre o porcelanato', 'Similar',
  'Insert interno invisível — não interfere na estética da fachada. Aço inox AISI 304 com laudos SENAI/LAMAT. Segurança redundante entre argamassa e revestimento.',
  'Grampo externo visível — compromete estética. Método mecânico que depende de furação no porcelanato acabado, risco de trinca.'
WHERE NOT EXISTS (SELECT 1 FROM portfolio_concorrentes WHERE concorrente = 'CFX RAI-FIX');
