INSERT INTO portfolio_normas (norma, orgao, titulo, status, segmentos, penalidade, observacao) VALUES
('Portaria MAPA 368/1997', 'MAPA', 'Regulamento Técnico sobre Boas Práticas de Fabricação para Estabelecimentos Produtores de Alimentos', 'vigente', ARRAY['Indústria Alimentícia','Frigorífico','Laticínio','Cervejaria'], 'Interdição do estabelecimento pelo SIF — suspensão imediata do registro e proibição de comercialização', 'Exige superfícies de contato com alimentos em material liso, impermeável, lavável e resistente — aço inox é o padrão aceito. Art. 5.2.'),
('IN MAPA 05/2017', 'MAPA', 'Requisitos para registro de estabelecimentos junto ao SIF', 'vigente', ARRAY['Indústria Alimentícia','Frigorífico'], 'Indeferimento do pedido de registro — estabelecimento não pode operar', 'Define requisitos de instalações e equipamentos para aprovação do SIF. Bancadas, mesas, tanques e tubulações devem ser em aço inoxidável.'),
('RDC ANVISA 275/2002', 'ANVISA', 'Regulamento Técnico de POP e Lista de Verificação de Boas Práticas', 'vigente', ARRAY['Indústria Alimentícia','Frigorífico','Laticínio','Cervejaria','Restaurantes'], 'Advertência, multa de R$ 2.000 a R$ 1.500.000 ou interdição (Lei 6.437/77)', 'Checklist de BPF inclui verificação de superfícies de contato: devem ser lisas, impermeáveis, laváveis. Inox é o material de referência.'),
('RDC ANVISA 216/2004', 'ANVISA', 'Regulamento Técnico de Boas Práticas para Serviços de Alimentação', 'vigente', ARRAY['Restaurantes','Indústria Alimentícia','Cervejaria','Padaria'], 'Multa de R$ 2.000 a R$ 1.500.000, interdição parcial ou total', 'Aplicável a cozinhas industriais e serviços de alimentação. Equipamentos devem ter superfícies lisas, impermeáveis, laváveis.'),
('ABNT NBR 14900:2002', 'ABNT', 'Sistema de gestão APPCC — Segurança de alimentos', 'vigente', ARRAY['Indústria Alimentícia','Frigorífico','Laticínio'], 'Perda de certificação — impacta exportação e contratos com grandes redes', 'O APPCC exige identificação de perigos. Superfícies em material inadequado são perigo físico/químico. Inox elimina esse ponto crítico.'),
('Codex Alimentarius CAC/RCP 1-1969', 'FAO/OMS', 'Princípios Gerais de Higiene dos Alimentos', 'vigente', ARRAY['Indústria Alimentícia','Frigorífico','Laticínio'], 'Barreiras à exportação — rejeição de lotes por importadores', 'Base para legislações nacionais. Seção 4.2: superfícies de contato devem ser de material não tóxico, resistente à corrosão.'),
('IN MAPA 76/2018', 'MAPA', 'Regulamento Técnico de Identidade e Qualidade de Leite Cru Refrigerado', 'vigente', ARRAY['Laticínio','Indústria Alimentícia'], 'Suspensão da captação de leite — paralisação da produção', 'Tanques de resfriamento e tubulações devem ser em aço inox. Contato com outros metais causa contaminação.'),
('IN MAPA 77/2018', 'MAPA', 'Regulamento Técnico de Identidade e Qualidade de Leite Pasteurizado', 'vigente', ARRAY['Laticínio','Indústria Alimentícia'], 'Recolhimento de lotes + suspensão do SIF', 'Pasteurizadores, tanques e envasadoras devem ser em aço inox 304 ou 316.')
ON CONFLICT (norma) DO UPDATE SET
  segmentos = EXCLUDED.segmentos,
  penalidade = EXCLUDED.penalidade,
  observacao = EXCLUDED.observacao;
